### ISSUE TITLE
Auto-scroll to bottom while outputting

### ISSUE THREAD

**Issue by samuel-jeffs** [QDAP-DATAAI/qchat#88]
When QChat is outputting text, the browser automatically scrolls to the bottom. This prevents a user from reading the top of a response while output is ongoing and forces the user to wait for the output to fully complete before they can scroll up and start reading.

I recommend having the scroll-to-bottom function only kick in when the model starts output, and not for every token that is output.

**Comment by kpqdap** [comment]
@samuel-jeffs this has been deployed and will be released today - thanks for the issue!
